### PR TITLE
Check the URL case insensitive

### PR DESCRIPTION
**Pull request by soulgalore**
Checkout #56, puh.

### CODE REVIEW

**Comment by soulgalore** [comment]
@tobli do you see any risk of doing this change?

**Comment by soulgalore** [comment]
screen shot 2018-02-07 at 1 24 45 pm

**Comment by tobli** [comment]
Adding a test case (a problematic har) would be nice for this as well.

**Comment by tobli** [comment]
The if statement just below should use the same comparison method, right?

One difference with using the url parser, instead of string comparison, is how trailing slash is handled. Now foo.com and foo.com/ will be equal. Is that something we want or not in this case? A server that sends a redirect to /, is that a thing? Haven't looked enough at this to think through the consequences.

**Comment by soulgalore** [comment]
Hmmm, true, we should look into that before we merge.

**Pull request merged**
