### PR TITLE
Collect requests loaded after onContentLoad and onLoad #17

### PR DESCRIPTION
**Pull request by soulgalore**

### CODE REVIEW

**Comment by soulgalore** [comment]
Let me know @beenanner when you have time to test this, want your input!

**Comment by beenanner** [comment]
I'll be able to test this weekend for sure

**Comment by soulgalore** [comment]
Great. @beenanner need you to think how we actually should use it. Right now we report requests after DOMContentLoaded and after onLoad (and DOMContentLoaded includes onLoad). We don't report before DOMContent so you need to calculate that yourself ... maybe not perfect.

**Comment by soulgalore** [comment]
@beenanner I'm pushing this now so I can try it out, check it out when you have time!

**Pull request merged**
