### PR TITLE
Minor clean up of TODOs and ES6 function short syntax

### PR DESCRIPTION
**Pull request by beenanner**
Converting lib functions to new es6 short syntax. Adding fix for document redirects. Returning 0 for both no domain redirects or time since modified header

### CODE REVIEW

**Comment by soulgalore** [comment]
Hey Jonathan,
thinking about:
> If time since last modified header is missing return 0 for value instead of -1

I put -1 there on purpose to make distinction wether it's set to 0 or we miss one, but maybe that is the same, need to check the spec, I don't have it in my head do you?

**Comment by beenanner** [comment]
Ah yes I see your point. I don't see anything in the spec, so I can revert that change back to -1. 

https://tools.ietf.org/html/rfc7232#section-2.2

I think the setting to "0" is also messing with the stats for the "lastModifiedStats" in the JSON output as well. Let's hold off on merging this and I'll dig into that later tonight.

*master branch* 
```
"lastModifiedStats": {
      "min": "327555",
      "p10": "327555",
      "median": "2582647",
      "p90": "130782020",
      "p99": "130782020",
      "max": "130782020"
    }
```

*time_since branch*
```
"lastModifiedStats": {
      "min": "0",
      "p10": "0",
      "median": "1163159",
      "p90": "24030024",
      "p99": "130782015",
      "max": "130782015"
    }
```

**Comment by soulgalore** [comment]
Maybe we could just have it undefined? One small thing: when we add a new release in the changelog and we don't now when it will be released, we call it UNRELEASED and then we do the release we change that to the number (when we know which it would be).

Btw good that you fixed the number of redirects, I missed that!

**Comment by beenanner** [comment]
Yep I think 'undefined' is the right way to go as it removes the key from the output for that asset. I've also seen negative numbers return which means the last 
modified was set to a date in the future which is against the spec. 

> An origin server with a clock MUST NOT send a Last-Modified date that
   is later than the server's time of message origination (Date).  If
   the last modification time is derived from implementation-specific

That would probably be a nice check in coach to flag those to the users to fix if possible. I'll file a ticket over on there for possibly implementing that check.

**Comment by beenanner** [comment]
Closing this old ticket out I think most of these issues have been fixed in other branches :-) + #20 is changing several things as well. :-)

**Pull request closed without merging**
